[build]
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
